### ISSUE TITLE
Be AWARE

### ISSUE THREAD

**Issue by TheCuteOwl** [ItzMati/FemboyGuessingBot#2]
we can see some personal info in a file, remove them

**Comment by TheCuteOwl** [comment]
![image](https://user-images.githubusercontent.com/114611129/229287448-cb009d7e-4078-4937-b125-af278846e38f.png)

**Comment by TheCuteOwl** [comment]
Angel Dust#0001

if u need any help DM me Angel Dust#0001 on discord

**Comment by ItzMati** [comment]
damn idk how i messed that up

it should be fixed now and I changed the password

thx for letting me know

**Comment by TheCuteOwl** [comment]
No problem ;)
